'use client'

import { useChat, type Message } from 'ai/react'
import { Howl, Howler } from 'howler'
import { cn } from '@/lib/utils'
import { ChatList } from '@/components/chat-list'
import { ChatPanel } from '@/components/chat-panel'
import { EmptyScreen } from '@/components/empty-screen'
import { ChatScrollAnchor } from '@/components/chat-scroll-anchor'
import { useLocalStorage } from '@/lib/hooks/use-local-storage'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog'
import { useMemo, useState } from 'react'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { toast } from 'react-hot-toast'
import { useVoices } from '@/contexts/VoiceContext'
import { AiVoiceSchema } from '@/lib/models'

const IS_PREVIEW = process.env.VERCEL_ENV === 'preview'
export interface ChatProps extends React.ComponentProps<'div'> {
  initialMessages?: Message[]
  id?: string
  modelId: AiVoiceSchema['model_id']
}

const getAiVoice = (id: string, voices: AiVoiceSchema[]) => {
  return voices.find(voice => voice.model_id === id)
}

function cleanMessage(message: string): string {
  // Replace newlines and carriage returns with spaces
  let cleanedMessage = message.replace(/[\r\n]+/g, ' ')

  // Remove any non-alphanumeric characters, except spaces, periods, commas, exclamation marks, and question marks.
  cleanedMessage = cleanedMessage.replace(/[^a-zA-Z0-9 .,!?]/g, '').trim()

  // Use encodeURIComponent to ensure safe usage in URL
  return encodeURIComponent(cleanedMessage)
}

const nonVerbalCues = [
  "nods",
  "shakes head",
  "raises an eyebrow",
  "furrows brow",
  "blinks rapidly",
  "smiles",
  "frowns",
  "grimaces",
  "pouts",
  "blushes",
  "rolls eyes",
  "stares",
  "looks away",
  "avoids eye contact",
  "makes prolonged eye contact",
  "points",
  "waves",
  "shrugs",
  "sighs",
  "yawns",
  "groans",
  "whistles",
  "purses lips",
  "bites lip",
  "licks lips",
  "crosses arms",
  "uncrosses arms",
  "taps foot",
  "drums fingers",
  "snaps fingers",
  "claps",
  "slaps thigh",
  "rubs chin",
  "scratches head",
  "tugs ear",
  "brushes hair back",
  "flips hair",
  "adjusts tie",
  "fixes collar",
  "straightens clothes",
  "checks watch",
  "adjusts glasses",
  "removes glasses",
  "rubs temples",
  "stretches",
  "leans in",
  "leans away",
  "tilts head",
  "hunches shoulders",
  "pushes up sleeves",
  "crosses legs",
  "uncrosses legs",
  "shuffles feet",
  "takes a deep breath",
  "exhales sharply",
  "coughs",
  "clears throat",
  "sneezes",
  "whimpers",
  "laughs",
  "cries",
  "paces",
  "sits down",
  "stands up",
  "jumps",
  "shivers",
  "trembles",
  "sweats",
  "blows a kiss",
  "rubs hands together",
  "cracks knuckles",
  "rubs neck",
  "massages shoulders",
  "pats back",
  "waves dismissively",
  "gives a thumbs up",
  "gives a thumbs down",
  "points thumbs toward self",
  "punches air",
  "makes a fist",
  "opens hand wide",
  "sniffs",
  "wrinkles nose",
  "covers mouth",
  "holds stomach",
  "rubs eyes",
  "tears up",
  "holds hands together in prayer",
  "fidgets",
  "spins an object",
  "twirls hair",
  "taps on a surface",
  "rocks back and forth",
  "bounces on heels",
  "swings arms while walking",
  "holds face in hands",
  "slouches",
  "stands tall",
  "salutes",
  "holds hand over heart",
  "places hands on hips",
  "wipes away tears",
  "covers ears",
  "points to self",
  "touches nose",
  "snaps to attention",
  "stomps foot",
  "winks both eyes",
  "ruffles someone's hair",
  "places finger on lips for silence",
  "nods",
  "shakes",
  "raises",
  "furrows",
  "blinks",
  "smiles",
  "frowns",
  "grimaces",
  "pouts",
  "blushes",
  "rolls",
  "stares",
  "glares",
  "glances",
  "peeks",
  "avoids",
  "points",
  "waves",
  "shrugs",
  "sighs",
  "yawns",
  "groans",
  "whistles",
  "purses",
  "bites",
  "licks",
  "crosses",
  "uncrosses",
  "taps",
  "drums",
  "snaps",
  "claps",
  "slaps",
  "rubs",
  "scratches",
  "tugs",
  "brushes",
  "flips",
  "adjusts",
  "fixes",
  "straightens",
  "checks",
  "removes",
  "leans",
  "tilts",
  "hunches",
  "pushes",
  "shuffles",
  "inhales",
  "exhales",
  "coughs",
  "clears",
  "sneezes",
  "whimpers",
  "laughs",
  "cries",
  "paces",
  "sits",
  "stands",
  "jumps",
  "shivers",
  "trembles",
  "sweats",
  "blows",
  "cracks",
  "massages",
  "pats",
  "waves",
  "gives",
  "punches",
  "makes",
  "opens",
  "sniffs",
  "wrinkles",
  "covers",
  "holds",
  "fidgets",
  "spins",
  "twirls",
  "rocks",
  "bounces",
  "swings",
  "slouches",
  "salutes",
  "wipes",
  "points",
  "touches",
  "snaps",
  "stomps",
  "excitedly",
  "grins",
  "grin",
  "wink",
  "winks",
  "ruffles",
  "giggles",
  "chuckles",
  "murmurs",
  "whispers",
  "hoots",
  "moans",
  "winces",
  "flinches",
  "squints",
  "stares",
  "peers",
  "blinks",
  "glares",
  "scowls",
  "beams",
  "smirks",
  "gapes",
  "glowers",
  "flicks",
  "waggles",
  "wiggles",
  "jiggles",
  "shrinks",
  "expands",
  "floats",
  "slinks",
  "struts",
  "hops",
  "skips",
  "trots",
  "scurries",
  "slides",
  "dashes",
  "prances",
  "lounges",
  "strides",
  "stalks",
  "ambles",
  "saunters",
  "meanders",
  "limps",
  "marches",
  "trudges",
  "stumbles",
  "totter",
  "wanders",
  "wobbles",
  "zigzags",
  "strolls",
  "tiptoes",
  "hurdles",
  "vaults",
  "lunges",
  "dives",
  "dodges",
  "flees",
  "pursues",
  "chases",
  "sprints",
  "jogs",
  "hurdles",
  "vaults",
  "gallops",
  "bounds",
  "leaps",
  "jumps",
  "soars",
  "swoops",
  "flies",
  "plunges",
  "falls",
  "sinks",
  "collapses",
  "crumples",
  "crashes",
  "smashes",
  "cracks",
  "ruptures",
  "bursts",
  "explodes",
  "shatters",
  "splinters",
  "breaks",
  "fractures",
  "splinters",
  "shreds",
  "rips",
  "tears",
  "shreds",
  "slices",
  "cuts",
  "chops",
  "dices",
  "carves",
  "hacks",
  "slashes",
  "saws",
  "pins",
  "nails",
  "staples",
  "tacks",
  "sticks",
  "stabs",
  "spikes",
  "skewers",
  "impales",
  "pierces",
  "pricks",
  "prods",
  "jabs",
  "pokes",
  "thrusts",
  "plunges",
  "rams",
  "drives",
  "hammers",
  "batters",
  "smashes",
  "crushes",
  "mashes",
  "grinds",
  "shreds",
  "mangles",
  "mauls",
  "tears",
  "ravages",
  "devastates",
  "ruins",
  "wrecks",
  "demolishes",
  "obliterates",
  "destroys",
  "eradicates",
  "exterminates",
  "slaughters",
  "massacres",
  "decimates",
  "eliminates",
  "murders",
  "kills",
  "assassinates",
  "executes",
  "terminates",
  "dispatches",
  "slays",
  "puts",
  "ends",
  "finishes",
  "completes",
  "consummates",
  "performs",
  "conducts",
  "accomplishes",
  "achieves",
  "fulfills",
  "realizes",
  "attains",
  "hits",
  "strikes",
  "beats",
  "bashes",
  "bangs",
  "slaps",
  "punches",
  "kicks",
  "knocks",
  "thumps",
  "whacks",
  "spanks",
  "slams",
  "whips",
  "lashes",
  "flogs",
  "pummels",
  "pounds",
  "batters",
  "hammers",
  "smashes",
  "bashes",
  "crushes",
  "mashes",
  "squeezes",
  "pinches",
  "presses",
  "compresses",
  "squashes",
  "crushes",
  "mashes",
  "grinds",
  "stomps",
  "tramples",
  "steps",
  "walks",
  "treads",
  "marches",
  "parades",
  "processions",
  "troops",
  "squadrons",
  "units",
  "groups",
  "teams",
  "crews",
  "gangs",
  "posses",
  "bands",
  "parties",
  "bunches",
  "lots",
  "masses",
  "hordes",
  "mobs",
  "crowds",
  "throng",
  "flocks",
  "herds",
  "swarms",
  "shoals",
  "schools",
  "packs",
  "troops",
  "brigades",
  "regiments",
  "battalions",
  "divisions",
  "corps",
  "forces",
  "armies",
  "navies",
  "air",
  "forces",
  "marines",
  "commands",
  "units",
  "squads",
  "crews",
  "teams",
  "gangs",
  "bands",
  "groups",
  "organizations",
  "companies",
  "firms",
  "corporations",
  "agencies",
  "institutions",
  "establishments",
  "enterprises",
  "ventures",
  "operations",
  "projects",
  "endeavors",
  "laughs",
  "smirks",
  "tasks",
  "missions",
  "quests",
  "pursuits",
  "efforts",
  "attempts",
  "tries",
  "stabs",
  "whirls",
  "shots",
  "cracks",
  "goes",
  "undertakings",
  "works",
  "jobs",
  "chores",
  "duties",
  "functions",
  "roles",
  "posts",
  "positions",
  "appointments",
  "offices",
  "stints",
  "shifts",
  "turns",
  "spells",
  "tours",
  "rounds",
  "routes",
  "beats",
  "tracks",
  "paths",
  "ways",
  "courses",
  "routes",
  "lines",
  "lanes",
  "avenues",
  "boulevards",
  "streets",
  "roads",
  "highways",
  "freeways",
  "motorways",
  "expressways",
  "driveways",
  "parkways",
  "passages",
  "corridors",
  "halls",
  "aisles",
  "walkways",
  "footpaths",
  "sidewalks",
  "pavements",
  "trails",
  "tracks",
  "paths",
  "routes",
  "ways",
  "courses",
  "lanes",
  "routes",
  "trails",
  "tracks",
  "footprints",
  "prints",
  "marks",
  "imprints",
  "stamps",
  "signs",
  "symbols",
  "signals",
  "indications",
  "hints",
  "tips",
  "clues",
  "leads",
  "pointers",
  "guidelines",
  "directions",
  "instructions",
  "orders",
  "commands",
  "demands",
  "requests",
  "pleas",
  "entreaties",
  "supplications",
  "prayers",
  "appeals",
  "calls",
  "cries",
  "shouts",
  "screams",
  "yells",
  "hollers",
  "bellows",
  "roars",
  "whoops",
  "hoots",
  "whistles",
  "sighs",
  "groans",
  "moans",
  "cries",
  "weeps",
  "sobs",
  "laughs",
  "giggles",
  "chuckles",
  "snickers",
  "guffaws",
  "laughs",
  "sniggers",
  "titters",
  "howls",
  "roars",
  "screams",
  "shrieks",
  "yells",
  "hollers",
  "bellows",
  "cries",
  "calls",
  "shouts",
  "exclaims",
  "declares",
  "proclaims",
  "announces",
  "states",
  "says",
  "speaks",
  "tells",
  "expresses",
  "voices",
  "utters",
  "pronounces",
  "enunciates",
  "articulates",
  "vocalizes",
  "sounds",
  "resounds",
  "echoes",
  "reverberates",
  "rings",
  "chimes",
  "peals",
  "clangs",
  "clashes",
  "clanks",
  "bangs",
  "booms",
  "blasts",
  "explosions",
  "detonations",
  "eruptions",
  "outbursts",
  "breakouts",
  "flare-ups",
  "blows",
  "spurts",
  "jets",
  "streams",
  "gushes",
  "fountains",
  "showers",
  "sprays",
  "sprinkles",
  "mists",
  "fogs",
  "vapors",
  "steams",
  "smokes",
  "puffs",
  "clouds",
  "hazes",
  "muddles",
  "confuses",
  "bewilders",
  "perplexes",
  "puzzles",
  "baffles",
  "flummoxes",
  "dumbfounds",
  "stumps",
  "mystifies",
  "confounds",
  "astounds",
  "amazes",
  "surprises",
  "shocks",
  "stuns",
  "dazes",
  "blinds",
  "excitedly",
  "overwhelms",
  "overpowers",
  "overcomes",
  "swamps",
  "engulfs",
  "immerses",
  "submerges",
  "drowns",
  "floods",
  "deluges",
  "inundates",
  "overruns",
  "swarms",
  "infests",
  "invades",
  "penetrates",
  "pierces",
  "perforates",
  "punctures",
  "pricks",
  "prods",
  "jabs",
  "pokes",
  "stabs",
  "slashes",
  "slices",
  "dices",
  "chops",
  "cuts",
  "carves",
  "shreds",
  "rips",
  "tears",
  "slashes",
  "wounds",
];


export function Chat({ id, modelId, initialMessages, className }: ChatProps) {
  const { voices } = useVoices()

  const voice = useMemo(() => getAiVoice(modelId, voices), [modelId, voices])
  const [previewToken, setPreviewToken] = useLocalStorage<string | null>(
    'ai-token',
    null
  )
  const [previewTokenDialog, setPreviewTokenDialog] = useState(IS_PREVIEW)
  const [previewTokenInput, setPreviewTokenInput] = useState(previewToken ?? '')
  const { messages, append, reload, stop, isLoading, input, setInput } =
    useChat({
      initialMessages,
      id,
      body: {
        id,
        previewToken
      },
      onFinish(message) {
        var old_message = message.content.trim()
        nonVerbalCues.forEach((cue) => {
          old_message = old_message.replace(" "+ cue + " ", '')
          old_message = old_message.replace(" "+ cue.substring(0, cue.length - 1) + " ", '')
          
        })
        message.content = old_message
        console.log(`Finished`, old_message)
        if (!voice) return
        const sound = new Howl({
          format: ['webm', 'mp3'],
          volume: 1,
          html5: true,
          src: [
            `${process.env.NEXT_PUBLIC_TTS_API_URL}?voice=${
              voice.name
            }&text=${cleanMessage(old_message)}`
          ]
        })
        sound.play()
      },
      onResponse(response) {
        console.log(response)
        if (response.status === 401) {
          toast.error(response.statusText)
        }
      }
    })
  return (
    <>
      <div className={cn('pb-[200px] pt-4 md:pt-10', className)}>
        {messages.length ? (
          <>
            <ChatList
              image={voice && voice.image_thumbnail_url}
              messages={messages}
            />
            <ChatScrollAnchor trackVisibility={isLoading} />
          </>
        ) : (
          <EmptyScreen setInput={setInput} />
        )}
      </div>
      <ChatPanel
        id={id}
        isLoading={isLoading}
        stop={stop}
        append={append}
        reload={reload}
        messages={messages}
        input={input}
        setInput={setInput}
      />

      <Dialog open={previewTokenDialog} onOpenChange={setPreviewTokenDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Enter your OpenAI Key</DialogTitle>
            <DialogDescription>
              If you have not obtained your OpenAI API key, you can do so by{' '}
              <a
                href="https://platform.openai.com/signup/"
                className="underline"
              >
                signing up
              </a>{' '}
              on the OpenAI website. This is only necessary for preview
              environments so that the open source community can test the app.
              The token will be saved to your browser&apos;s local storage under
              the name <code className="font-mono">ai-token</code>.
            </DialogDescription>
          </DialogHeader>
          <Input
            value={previewTokenInput}
            placeholder="OpenAI API key"
            onChange={e => setPreviewTokenInput(e.target.value)}
          />
          <DialogFooter className="items-center">
            <Button
              onClick={() => {
                setPreviewToken(previewTokenInput)
                setPreviewTokenDialog(false)
              }}
            >
              Save Token
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}
